"""
Portfolio AI Advisor - 보유종목 AI 피드백 시스템
매일 AI가 투자 판단을 제시하고, 다음날 결과로 검증

검증 주기: 1일 (어제 판단 → 오늘 결과)
AI: Google Gemini API 사용
"""
import asyncio
import os
from datetime import datetime, timedelta
from decimal import Decimal
from typing import Optional, Dict, Any, List

import google.generativeai as genai

import sys
sys.path.insert(0, '/Users/wonny/Dev/joungwon.stocks')
from src.config.database import db


class PortfolioAdvisor:
    """보유종목 AI 피드백 어드바이저"""

    RECOMMENDATION_MAP = {
        'BUY_MORE': '추가 매수',
        'HOLD': '관망',
        'SELL': '일부 매도',
        'CUT_LOSS': '손절'
    }

    RECOMMENDATION_EMOJI = {
        'BUY_MORE': '🟢',
        'HOLD': '⚪',
        'SELL': '🟡',
        'CUT_LOSS': '🔴'
    }

    def __init__(self):
        # Configure Gemini API
        api_key = os.getenv('GEMINI_API_KEY')
        if api_key:
            genai.configure(api_key=api_key)
            self.model = genai.GenerativeModel('gemini-2.0-flash-lite')
        else:
            self.model = None
            print("⚠️ GEMINI_API_KEY not set - PortfolioAdvisor will not work")

    async def check_cache(self, stock_code: str) -> Optional[Dict[str, Any]]:
        """오늘 이미 생성된 AI 판단이 있는지 캐시 확인"""
        query = """
            SELECT recommendation, rationale, confidence
            FROM portfolio_ai_history
            WHERE stock_code = $1 AND report_date = CURRENT_DATE
        """
        result = await db.fetchrow(query, stock_code)
        if result:
            print(f"💾 캐시 적중: {stock_code} (오늘 데이터 재사용)")
            return {
                'recommendation': result['recommendation'],
                'rationale': result['rationale'],
                'confidence': float(result['confidence']) if result['confidence'] else 0.5,
                'review': '',
                'source': 'cache'
            }
        return None

    def generate_fallback_strategy(
        self,
        return_rate: float,
        investor_data: Optional[Dict] = None
    ) -> Dict[str, Any]:
        """
        API 실패 시 규칙 기반 Fallback 전략 생성

        규칙:
        - 손실률 -10% 미만 + 외국인 매수 → BUY_MORE
        - 손실률 -10% 미만 + 매도세 → HOLD
        - 수익률 +10% 초과 → SELL
        - 기타 → HOLD
        """
        foreign_5d = investor_data.get('foreign_5d', 0) if investor_data else 0
        institutional_5d = investor_data.get('institutional_5d', 0) if investor_data else 0

        recommendation = 'HOLD'
        rationale = '특이 사항이 없어 현 추세를 관망합니다.'
        confidence = 0.4

        if return_rate < -10:
            if foreign_5d > 0:
                recommendation = 'BUY_MORE'
                rationale = '낙폭 과대 구간에서 외국인 수급이 유입되고 있어 분할 매수 기회로 보입니다.'
                confidence = 0.5
            else:
                recommendation = 'HOLD'
                rationale = '하락세가 지속되고 있어 바닥 확인 전까지 관망을 권장합니다.'
                confidence = 0.4
        elif return_rate > 10:
            recommendation = 'SELL'
            rationale = '목표 수익률 도달 가능성이 높으므로 부분 이익 실현을 고려하세요.'
            confidence = 0.6
        elif return_rate < -5 and (foreign_5d > 0 or institutional_5d > 0):
            recommendation = 'BUY_MORE'
            rationale = '조정 구간에서 기관/외국인 매수세가 감지됩니다. 분할 매수 고려 가능합니다.'
            confidence = 0.45

        rationale += ' *(Note: AI quota exceeded. Strategy generated by quantitative rules.)*'

        print(f"🔄 Fallback 전략 적용: {recommendation}")
        return {
            'recommendation': recommendation,
            'rationale': rationale,
            'confidence': confidence,
            'review': '',
            'source': 'fallback'
        }

    async def get_yesterday_advice(self, stock_code: str) -> Optional[Dict[str, Any]]:
        """어제의 AI 판단을 조회 (검증되지 않은 것)"""
        query = """
            SELECT id, stock_code, report_date, my_avg_price, market_price, return_rate,
                   recommendation, rationale, confidence, is_verified,
                   next_day_price, next_day_return, was_correct, created_at, verified_at
            FROM portfolio_ai_history
            WHERE stock_code = $1
              AND report_date = CURRENT_DATE - INTERVAL '1 day'
              AND is_verified = FALSE
            ORDER BY created_at DESC
            LIMIT 1
        """
        result = await db.fetchrow(query, stock_code)
        return dict(result) if result else None

    async def get_latest_advice(self, stock_code: str) -> Optional[Dict[str, Any]]:
        """가장 최근 AI 판단을 조회 (오늘 것 포함)"""
        query = """
            SELECT id, stock_code, report_date, my_avg_price, market_price, return_rate,
                   recommendation, rationale, confidence, is_verified,
                   next_day_price, next_day_return, was_correct, created_at, verified_at
            FROM portfolio_ai_history
            WHERE stock_code = $1
            ORDER BY report_date DESC, created_at DESC
            LIMIT 1
        """
        result = await db.fetchrow(query, stock_code)
        return dict(result) if result else None

    async def verify_yesterday_advice(self, stock_code: str, today_price: float) -> Optional[Dict[str, Any]]:
        """
        어제 판단을 오늘 가격으로 검증

        검증 로직:
        - BUY_MORE 추천 → 오늘 상승했으면 was_correct = TRUE
        - SELL/CUT_LOSS 추천 → 오늘 하락했으면 was_correct = TRUE
        - HOLD 추천 → 변동폭 ±1% 이내면 was_correct = TRUE
        """
        yesterday = await self.get_yesterday_advice(stock_code)
        if not yesterday:
            return None

        yesterday_price = float(yesterday['market_price'])
        next_day_return = ((today_price - yesterday_price) / yesterday_price) * 100

        recommendation = yesterday['recommendation']
        was_correct = False

        if recommendation == 'BUY_MORE':
            was_correct = next_day_return > 0  # 상승하면 적중
        elif recommendation in ['SELL', 'CUT_LOSS']:
            was_correct = next_day_return < 0  # 하락하면 적중
        elif recommendation == 'HOLD':
            was_correct = abs(next_day_return) <= 1.0  # ±1% 이내면 적중

        # DB 업데이트
        update_query = """
            UPDATE portfolio_ai_history
            SET is_verified = TRUE,
                next_day_price = $1,
                next_day_return = $2,
                was_correct = $3,
                verified_at = NOW()
            WHERE id = $4
        """
        await db.execute(update_query, today_price, next_day_return, was_correct, yesterday['id'])

        # 업데이트된 결과 반환
        yesterday['next_day_price'] = today_price
        yesterday['next_day_return'] = next_day_return
        yesterday['was_correct'] = was_correct
        yesterday['is_verified'] = True

        return yesterday

    async def generate_strategy(
        self,
        stock_code: str,
        stock_name: str,
        avg_buy_price: float,
        current_price: float,
        investor_data: Optional[Dict] = None,
        news_summary: Optional[str] = None,
        yesterday_advice: Optional[Dict] = None,
        price_history: Optional[List[Dict]] = None,
        use_cache: bool = True
    ) -> Dict[str, Any]:
        """
        Gemini AI를 사용하여 오늘의 투자 전략 생성

        Args:
            stock_code: 종목코드
            stock_name: 종목명
            avg_buy_price: 평균 매수가
            current_price: 현재가
            investor_data: 수급 데이터 (외국인/기관 순매수)
            news_summary: 최근 뉴스 요약
            yesterday_advice: 어제 AI 판단 및 검증 결과
            price_history: 최근 가격 이력
            use_cache: 캐시 사용 여부 (기본: True)

        Returns:
            {
                'recommendation': 'BUY_MORE' | 'HOLD' | 'SELL' | 'CUT_LOSS',
                'rationale': str,
                'confidence': float (0.0 ~ 1.0),
                'review': str (어제 판단에 대한 회고),
                'source': 'ai' | 'cache' | 'fallback'
            }
        """
        return_rate = ((current_price - avg_buy_price) / avg_buy_price) * 100

        # 1. 캐시 확인 (오늘 이미 분석한 데이터가 있으면 재사용)
        if use_cache:
            cached = await self.check_cache(stock_code)
            if cached:
                return cached

        # 2. Gemini API 미설정 시 Fallback
        if not self.model:
            print("⚠️ Gemini API 미설정 - Fallback 전략 사용")
            return self.generate_fallback_strategy(return_rate, investor_data)

        # 프롬프트 구성
        prompt = f"""당신은 엄격한 포트폴리오 매니저입니다. 다음 종목에 대한 투자 판단을 내려주세요.

## 종목 정보
- 종목명: {stock_name} ({stock_code})
- 내 평균 매수가: {int(avg_buy_price):,}원
- 현재가: {int(current_price):,}원
- 현재 수익률: {return_rate:+.2f}%
"""

        if price_history:
            prompt += "\n## 최근 가격 추이\n"
            for p in price_history[-10:]:
                prompt += f"- {p.get('date', 'N/A')}: {int(p.get('close', 0)):,}원"
                if p.get('change_pct'):
                    prompt += f" ({p['change_pct']:+.2f}%)"
                if p.get('volume'):
                    prompt += f" 거래량:{p['volume']:,}"
                prompt += "\n"

        if investor_data:
            prompt += f"""
## 수급 정보 (최근 5일)
- 외국인 순매수: {investor_data.get('foreign_5d', 0):+,}주
- 기관 순매수: {investor_data.get('institutional_5d', 0):+,}주
"""

        if news_summary:
            prompt += f"""
## 최근 뉴스 요약
{news_summary}
"""

        if yesterday_advice:
            prompt += f"""
## 어제 AI 판단 (검증 결과)
- 어제 의견: {self.RECOMMENDATION_MAP.get(yesterday_advice['recommendation'], '알 수 없음')}
- 어제 종가: {int(yesterday_advice['market_price']):,}원
- 오늘 종가: {int(yesterday_advice.get('next_day_price', current_price)):,}원
- 결과: {yesterday_advice.get('next_day_return', 0):+.2f}%
- 적중 여부: {'✅ 적중' if yesterday_advice.get('was_correct') else '❌ 실패'}
"""

        prompt += """
## 지시사항
1. 위 정보를 종합하여 다음 중 하나의 행동을 추천하세요:
   - BUY_MORE: 추가 매수 (저평가 구간, 수급 양호)
   - HOLD: 관망 (추세 불분명, 대기)
   - SELL: 일부 매도 (고점 근처, 차익실현)
   - CUT_LOSS: 손절 (하락 추세 지속, 손실 확대 방지)

2. 반드시 아래 JSON 형식으로만 응답하세요:
{
    "recommendation": "BUY_MORE" | "HOLD" | "SELL" | "CUT_LOSS",
    "rationale": "판단 이유를 한국어로 2-3문장으로 작성",
    "confidence": 0.0 ~ 1.0 사이의 신뢰도,
    "review": "어제 판단에 대한 회고 (있는 경우)"
}

JSON만 출력하세요. 다른 텍스트는 출력하지 마세요.
"""

        try:
            response = self.model.generate_content(prompt)
            response_text = response.text.strip()

            # JSON 파싱
            import json
            # JSON 블록 추출
            if '```json' in response_text:
                response_text = response_text.split('```json')[1].split('```')[0].strip()
            elif '```' in response_text:
                response_text = response_text.split('```')[1].split('```')[0].strip()

            result = json.loads(response_text)

            # 유효성 검사
            if result.get('recommendation') not in ['BUY_MORE', 'HOLD', 'SELL', 'CUT_LOSS']:
                result['recommendation'] = 'HOLD'

            result['confidence'] = max(0.0, min(1.0, float(result.get('confidence', 0.5))))
            result['source'] = 'ai'

            print(f"✅ Gemini AI 분석 완료: {result['recommendation']}")
            return result

        except Exception as e:
            print(f"❌ Gemini API 오류: {e}")
            # API 실패 시 Fallback 전략 사용
            return self.generate_fallback_strategy(return_rate, investor_data)

    async def save_decision(
        self,
        stock_code: str,
        avg_buy_price: float,
        market_price: float,
        recommendation: str,
        rationale: str,
        confidence: float
    ) -> int:
        """오늘의 AI 판단을 DB에 저장"""
        return_rate = ((market_price - avg_buy_price) / avg_buy_price) * 100

        query = """
            INSERT INTO portfolio_ai_history
                (stock_code, report_date, my_avg_price, market_price, return_rate,
                 recommendation, rationale, confidence)
            VALUES ($1, CURRENT_DATE, $2, $3, $4, $5, $6, $7)
            ON CONFLICT (stock_code, report_date)
            DO UPDATE SET
                my_avg_price = EXCLUDED.my_avg_price,
                market_price = EXCLUDED.market_price,
                return_rate = EXCLUDED.return_rate,
                recommendation = EXCLUDED.recommendation,
                rationale = EXCLUDED.rationale,
                confidence = EXCLUDED.confidence,
                created_at = NOW()
            RETURNING id
        """
        result = await db.fetchval(
            query,
            stock_code, avg_buy_price, market_price, return_rate,
            recommendation, rationale, confidence
        )
        return result

    async def get_verification_stats(self, stock_code: str, days: int = 30) -> Dict[str, Any]:
        """최근 N일간 AI 판단 적중률 통계"""
        query = """
            SELECT
                COUNT(*) as total,
                SUM(CASE WHEN was_correct THEN 1 ELSE 0 END) as correct,
                AVG(CASE WHEN was_correct THEN 1 ELSE 0 END) * 100 as accuracy,
                AVG(next_day_return) as avg_return
            FROM portfolio_ai_history
            WHERE stock_code = $1
              AND is_verified = TRUE
              AND report_date >= CURRENT_DATE - $2 * INTERVAL '1 day'
        """
        result = await db.fetchrow(query, stock_code, days)

        return {
            'total': result['total'] or 0,
            'correct': result['correct'] or 0,
            'accuracy': float(result['accuracy'] or 0),
            'avg_return': float(result['avg_return'] or 0)
        }

    async def process_daily_feedback(
        self,
        stock_code: str,
        stock_name: str,
        avg_buy_price: float,
        current_price: float,
        investor_data: Optional[Dict] = None,
        news_summary: Optional[str] = None,
        price_history: Optional[List[Dict]] = None
    ) -> Dict[str, Any]:
        """
        일일 피드백 전체 프로세스 실행
        1. 어제 판단 조회 및 검증
        2. 오늘 판단 생성
        3. DB 저장
        4. 결과 반환
        """
        # 1. 어제 판단 검증
        verified_yesterday = await self.verify_yesterday_advice(stock_code, current_price)

        # 2. 오늘 판단 생성
        today_strategy = await self.generate_strategy(
            stock_code=stock_code,
            stock_name=stock_name,
            avg_buy_price=avg_buy_price,
            current_price=current_price,
            investor_data=investor_data,
            news_summary=news_summary,
            yesterday_advice=verified_yesterday,
            price_history=price_history
        )

        # 3. DB 저장
        saved_id = await self.save_decision(
            stock_code=stock_code,
            avg_buy_price=avg_buy_price,
            market_price=current_price,
            recommendation=today_strategy['recommendation'],
            rationale=today_strategy['rationale'],
            confidence=today_strategy['confidence']
        )

        # 4. 결과 반환
        return {
            'stock_code': stock_code,
            'stock_name': stock_name,
            'yesterday_review': verified_yesterday,
            'today_strategy': today_strategy,
            'saved_id': saved_id
        }


# 테스트용
async def test_advisor():
    """테스트 실행"""
    await db.connect()
    try:
        advisor = PortfolioAdvisor()

        # 테스트 종목 (한국전력)
        result = await advisor.process_daily_feedback(
            stock_code='015760',
            stock_name='한국전력',
            avg_buy_price=22000,
            current_price=21500,
            investor_data={'foreign_5d': -50000, 'institutional_5d': 30000},
            news_summary='전기요금 인상 논의 중, 정부 정책 변화 예상'
        )

        print("\n===== AI 피드백 결과 =====")
        print(f"종목: {result['stock_name']}")

        if result['yesterday_review']:
            y = result['yesterday_review']
            print(f"\n[어제 회고]")
            print(f"  의견: {advisor.RECOMMENDATION_MAP.get(y['recommendation'])}")
            print(f"  결과: {y.get('next_day_return', 0):+.2f}%")
            print(f"  적중: {'✅' if y.get('was_correct') else '❌'}")

        t = result['today_strategy']
        print(f"\n[오늘 전략]")
        print(f"  추천: {advisor.RECOMMENDATION_EMOJI.get(t['recommendation'])} {advisor.RECOMMENDATION_MAP.get(t['recommendation'])}")
        print(f"  이유: {t['rationale']}")
        print(f"  신뢰도: {t['confidence']*100:.0f}%")

    finally:
        await db.disconnect()


if __name__ == '__main__':
    asyncio.run(test_advisor())
